matrixolver/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
	url(r'^inverse/solution/', views.inv_solution, name='inv_solution'),
	#url(r'^inverse/inv_get_size/', views.inv_get_size, name='inv_get_size'),
	url(r'^inverse/', views.inv_index, name='inv_index'),
	url(r'^rank/solution', views.rank_solution, name='rank_solution'),
	url(r'^rank/', views.rank, name='rank'),
	url(r'^system/solution', views.system_solution, name='system_solution'),
	url(r'^system/', views.system, name='system'),
	url(r'^eigen/solution', views.eigen_solution, name='eigen_solution'),
	url(r'^eigen/', views.eigen, name='eigen'),
	url(r'^personal/ukol_md', views.ukol_md, name='ukol_md'),
	url(r'^', views.index, name='index'),
	#url(r'^/table_size/', views.table_size, name='table_size'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('matrixolver.urls', namespace='matrixolver')),
]

matrixolver/models.py
from django.db import models

#from .matrix import Matrix as m_class
#
#
#class MatrixField(models.Field)
#	def __init__(self, *args, **kwargs):
#		kwargs['max_length'] = 104
#		super(MatrixField, self).__init__(*args,**kwargs)
#
#class Matrix(models.Model):
#	row_num = models.IntegerField()
#	col_num = models.IntegerField()
#
#	def associate(self):
#		cells = self.cell_set
#		flat_rows = [ cell.val for cell in cells ]
#		self.rows = []
#		for i in range (0,self.row_num):
#			for j in range(0,self.col_num):
#				self.rows[i][j] = flat_rows[i*self.col_num-1+j]
#		self.mat = m_class(self.rows)
#
#	def __str__(self):
#		return 'matrix'
#	#vsechny veci importovany z matrixu
#
#class Cell(models.Model):
#	matrix = models.ForeignKey(Matrix)
#	row = models.IntegerField()
#	col = models.IntegerField()
#	val = models.FloatField()
#
## Create your models here.

matrixolver/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404
from django.views.generic.base import TemplateView

from fractions import Fraction
from .matrix import Matrix, ExtendedMatrix, join
from .matrix_calls import inverse_call, rank_call, solvesys_call, eigenvals_call
from . import messages

import pdb
import numpy as np

def index(request):
	return render(request, 'matrixolver/index.html')

def inv_index(request):
	A = Matrix.zeros(size=(3,3))
	return render(request, 'matrixolver/inverse.html', {'A': A,})

#def inv_get_size(request):
#	if request.method == 'POST':
#		post = request.POST
#		row_num = int(request.POST.get('row_num', 4))
#		col_num = int(request.POST.get('col_num', 4))
#		A = Matrix.zeros(size=(row_num, col_num))
#		return render(request, 'matrixolver/inverse.html', {'A': A, 'post': post,})
#	return inv_index(request)
		
def inv_solution(request):
	if request.method == 'POST':
		row_num = int(request.POST.get('hidden_rows', 4))
		col_num = int(request.POST.get('hidden_cols', 5))
		rows = np.zeros((row_num,col_num), dtype=Fraction)
		for i in range(0, row_num):
			for j in range(0, col_num):
				cell_name = 'a'+str(i)+str(j)
				rows[i,j] = Fraction(request.POST.get(cell_name, 0.))
		A = Matrix(rows)
		result = inverse_call(A)
		if 'error' in result:
			print(result['error'])
			error_message = messages.error_message(result['error'])
			return render(request, 'matrixolver/inverse.html', {'sol': result['sol'], 'A': A, 'rows': rows, 'error': error_message['cz'],})
		else:
			return render(request, 'matrixolver/inverse.html', {'sol': result['sol'], 'A': A, 'rows': rows,})
	else: return inv_index(request)

def rank(request):
	A = Matrix.zeros(size=(4,4))
	return render(request, 'matrixolver/rank.html', {'A': A,})

def rank_solution(request):
	if request.method == 'POST':
		row_num = int(request.POST.get('hidden_rows', 4))
		col_num = int(request.POST.get('hidden_cols', 5))
		rows = np.zeros((row_num,col_num), dtype=Fraction)
		for i in range(0, row_num):
			for j in range(0, col_num):
				cell_name = 'a'+str(i)+str(j)
				rows[i,j] = Fraction(request.POST.get(cell_name, 0.))
		A = Matrix(rows)
		result = rank_call(A)
		if 'error' in result:
			error_message = messages.error_message(result['error'])
			return render(request, 'matrixolver/rank.html', {'sol': result['sol'], 'A': A, 'rows': rows, 'error': error_message['cz'],})
		else:
			return render(request, 'matrixolver/rank.html', {'sol': result['sol'], 'A': A, 'rows': rows,})
	else: return rank(request)

def system(request):
	A = Matrix.zeros(size=(3,3))
	vec = Matrix.zeros(size=(3,1))
	joined = join(A,vec)
	return render(request, 'matrixolver/syslineq.html', {'A': A, 'joined': joined,})

def system_solution(request):
	if request.method == 'POST':
		row_num = int(request.POST.get('hidden_rows', 4))
		col_num = int(request.POST.get('hidden_cols', 5))
		rows = np.zeros((row_num,col_num), dtype=Fraction)
		for i in range(0, row_num):
			for j in range(0, col_num):
				cell_name = 'a'+str(i)+str(j)
				rows[i,j] = Fraction(request.POST.get(cell_name, 0.))
		joined = Matrix(rows)
		result = solvesys_call(joined)
		if 'error' in result:
			error_message = messages.error_message(result['error'])
			return render(request, 'matrixolver/syslineq.html', {'sol': result['sol'], 'joined': joined, 'A': result['A'], 'rows': rows, 'error': error_message['cz'],})
		else:
			if 'param_tables' in result and 'params' in result:
				A = result['A']
				return render(request, 'matrixolver/syslineq.html', {'sol': result['sol'], 'joined': joined, 'A': A, 'dim': A.col_num, 'rank': A.rank(), 'param_tables': result['param_tables'], 'params': result['params']})
			else:
				return render(request, 'matrixolver/syslineq.html', {'sol': result['sol'], 'joined': joined, 'A': result['A'], 'rows': rows,})
	else: return system(request)
	
def eigen(request):
	A = Matrix.zeros(size=(3,3))
	return render(request, 'matrixolver/eigen.html', {'A': A})

def eigen_solution(request):
	if request.method == 'POST':
		row_num = int(request.POST.get('hidden_rows', 4))
		col_num = int(request.POST.get('hidden_cols', 5))
		rows = np.zeros((row_num,col_num), dtype=Fraction)
		for i in range(0, row_num):
			for j in range(0, col_num):
				cell_name = 'a'+str(i)+str(j)
				rows[i,j] = Fraction(request.POST.get(cell_name, 0.))
		A = Matrix(rows)
		result = eigenvals_call(A)
		return render(request, 'matrixolver/eigen.html', {'mathml': result['mathml'], 'A': A})
	else: return eigen(request)

def md_ukol(request):
    return render(request, 'personal/md_ukol.html')

# Create your views here.

matrixolver/templates/matrixolver/base.html
<!DOCTYPE html>
<html>
<head>
	<meta charset='UTF-8'>
	<title>Matrixolver</title>
{% load staticfiles %}

<link rel='stylesheet' type='text/css' href='{% static "matrixolver/style.css" %}'>
<script type='text/javascript' src='{% static "matrixolver/script.js" %}'></script>
<script type='text/javascript' src='{% static "matrixolver/modernizr.custom.37954.js" %}'></script>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

<!-- Google analytics script-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-66476808-1', 'auto');
  ga('send', 'pageview');

</script>
</head>

<body>
<style>
</style>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'matrixolver:index' %}">MATRIXOLVER</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li id='rank'><a href="{% url 'matrixolver:rank' %}">Hodnost matice</a></li>
        <li id='inv'><a href="{% url 'matrixolver:inv_index' %}">Inverzní matice</a></li>
        <li id='sys'><a href="{% url 'matrixolver:system' %}">Řešení soustav</a></li>
        <li id='eig'><a href="{% url 'matrixolver:eigen' %}">Vlastní čísla (alpha verze)</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<section>
{% block content %}
{% endblock %}
</section>

<footer>

</footer>
</div>
<body>

</html>

matrixolver/templates/matrixolver/eigen.html
	{% extends 'matrixolver/base.html' %}

{% block content %}

<script type='text/javascript'>
	lis = $('ul.nav').find('li');
	lis.removeClass('active');
	$('#eig').addClass('active');
	var row_num = {{ A.row_num }};
	var col_num = {{ A.col_num }};
</script>

<style>
	.affix{ top: 20px; }
</style>

<div class='container-fluid'>
	<div class='row' id='solution_row'>
			<div class='col-md-2 col-sm-3 well sidebar-nav-fixed' style='padding: 19px 0 !important;'>
			<div class='span1'> <!--potreba prijit na to, proc se meni sirka a vyresit overlap pri mensim rozliseni--!>
			<div class='row'>
			<div class='col'>
			<!--	<div class='cSize'>
				<form action='{}' method='POST'>{% csrf_token %}
					<label for='rows'>Rows</label>
					<input type='number' id='rows' name='row_num' autocomplete='off' min='1' />
					<label for='cols'>Columns</label>
					<input type='number' id='cols' name='col_num' autocomplete='off' min='1' />
					<input type='submit' value='set size' class='cSubmit' />
				</form>
				</div> --!>
			<div class='cSize'>
			<table>
			<tr>
				<td style='white-space: nowrap'>Velikost matice: <span id='PrintSize'>{{ A.row_num }}</span>&nbsp&nbsp</td>
				<td>
					<span class="btn-group-xs btn-group-vertical" role="group" aria-label="Velikost matice">
						<button type="button" class="btn btn-primary" id='sizePlus'>+</button>
						<button type="button" class="btn btn-primary" id='sizeMinus'>-</button>
					</span>
				</td>
			</tr>
			</table>
			</div>

			</div>
			</div>

			<div class='row'>
			<div class='col'>
				<div class='input-group cInput' id='sidebar'>
				<form action="{% url 'matrixolver:eigen_solution' %}" method='POST' name='matrix'>{% csrf_token %}
				<!--form validation--!>
					<table class='table table-bordered table-condensed' id='InputTable'>
					{% for row in A.rows %}
						<tr>{% for element in row %}<td>
				<input class='form-control cInput' type='text' name='a{{ forloop.parentloop.counter0 }}{{ forloop.counter0 }}' onclick='select()' step='any' value='{{ element }}' autocomplete='off' pattern='[-+]?[0-9]*\.?[0-9]*' /></td>{% endfor %}</tr>
					{% endfor %}
					</table>
					<input type='hidden'  id='hidden_rows' name='hidden_rows' value='{{ A.row_num }}' />
					<input type='hidden' id='hidden_cols' name='hidden_cols' value='{{ A.col_num }}' />
					<button type="submit" class='btn btn-primary'>Spočítat vlastní čísla</button>
				</form>
				</div>
			</div>
			</div>
			</div>
		</div>

<script>
	$( '#sizeMinus' ).click(function(){
															row_num -= 1;
															col_num -= 1;
															createInputTable(row_num, col_num);
															$( '#PrintSize' ).html(row_num);
															$( '#hidden_rows' ).val(row_num);
															$( '#hidden_cols' ).val(col_num);})

	$( '#sizePlus' ).click(function(){
															row_num += 1;
															col_num += 1;
															createInputTable(row_num, col_num);
															$( '#PrintSize' ).html(row_num);
															$( '#hidden_rows' ).val(row_num);
															$( '#hidden_cols' ).val(col_num);})
</script>
<!-- reseni bude v include --!>
<div class='col-md-10 col-sm-9' style='padding-right: 0 !important;'>
{% include 'matrixolver/eigen_solution.html' %}
</div>
	</div>
</div>
{% endblock content %}

matrixolver/templates/matrixolver/eigen_solution.html
{% load matrixolver_extras %}

			{% if mathml %}
<math xmlns="http://www.w3.org/1998/Math/MathML">
{% autoescape off %}
{{mathml}}
{% endautoescape %}
</math>
		{% endif %}

matrixolver/templates/matrixolver/index.html
{% extends 'matrixolver/base.html' %}

{% block content %}
<script type='text/javascript'>

	lis = $('ul.nav').find('li');
	lis.removeClass('active');
</script>

<h1>Vítej na MATRIXOLVERu</h1>

Budu postupně rozšiřovat jeho funkce. V tuto chvíli jsou v provozu následující funkce:
<ul>
	<li>výpočet hodnosti matice</li>
	<li>výpočet inverzní matice</li>
	<li>řešení soustav lineárních algebraických rovnic (včetně prostoru řešení)</li>
</ul>
Můj TODO list co dělat dál je následující
<ul>
	<li>umožnit zadávání zlomků</li>
	<li>násobení matic</li>
	<li>výpočet vlastních čísel a vektorů, diagonalizace matice, Jordanův tvar</li>
	<li>určit hodnost nebo počet řešení soustavy v závislosti na parametru</li>
	<li>transoformace bází</li>
</ul>

Pokud něco nefunguje, jak má, nebo chcete podpořit vývoj stránek, či máte jakoukoliv jinou připomínku, napište mi na <b>matrixolver(zavináč)gmail.com</b>

{% endblock content %}

matrixolver/templates/matrixolver/inverse.html
{% extends 'matrixolver/base.html' %}

{% block content %}

<script type='text/javascript'>
	lis = $('ul.nav').find('li');
	lis.removeClass('active');
	$('#inv').addClass('active');
	var row_num = {{ A.row_num }};
	var col_num = {{ A.col_num }};
</script>

<style>
	.affix{ top: 20px; }
</style>

<div class='container-fluid'>
	<div class='row' id='solution_row'>
			<div class='col-md-2 col-sm-3 well sidebar-nav-fixed' style='padding: 19px 0 !important;'>
			<div class='span1'> <!--potreba prijit na to, proc se meni sirka a vyresit overlap pri mensim rozliseni--!>
			<div class='row'>
			<div class='col'>
			<!--	<div class='cSize'>
				<form action='{}' method='POST'>{% csrf_token %}
					<label for='rows'>Rows</label>
					<input type='number' id='rows' name='row_num' autocomplete='off' min='1' />
					<label for='cols'>Columns</label>
					<input type='number' id='cols' name='col_num' autocomplete='off' min='1' />
					<input type='submit' value='set size' class='cSubmit' />
				</form>
				</div> --!>
			<div class='cSize'>
			<table>
			<tr>
				<td style='white-space: nowrap'>Velikost matice: <span id='PrintSize'>{{ A.row_num }}</span>&nbsp&nbsp</td>
				<td>
					<span class="btn-group-xs btn-group-vertical" role="group" aria-label="Velikost matice">
						<button type="button" class="btn btn-primary" id='sizePlus'>+</button>
						<button type="button" class="btn btn-primary" id='sizeMinus'>-</button>
					</span>
				</td>
			</tr>
			</table>
			</div>

			</div>
			</div>

			<div class='row'>
			<div class='col'>
				<div class='input-group cInput' id='sidebar'>
				<form action="{% url 'matrixolver:inv_solution' %}" method='POST' name='matrix'>{% csrf_token %}
				<!--form validation--!>
					<table class='table table-bordered table-condensed' id='InputTable'>
					{% for row in A.rows %}
						<tr>{% for element in row %}<td>
				<input class='form-control cInput' type='text' name='a{{ forloop.parentloop.counter0 }}{{ forloop.counter0 }}' onclick='select()' step='any' value='{{ element }}' autocomplete='off' pattern='[-+]?[0-9]*\.?[0-9]*' /></td>{% endfor %}</tr>
					{% endfor %}
					</table>
					<input type='hidden'  id='hidden_rows' name='hidden_rows' value='{{ A.row_num }}' />
					<input type='hidden' id='hidden_cols' name='hidden_cols' value='{{ A.col_num }}' />
					<button type="submit" class='btn btn-primary'>Spočítat inverzi</button>
				</form>
				</div>
			</div>
			</div>
			</div>
		</div>

<script>
	$( '#sizeMinus' ).click(function(){
															row_num -= 1;
															col_num -= 1;
															createInputTable(row_num, col_num);
															$( '#PrintSize' ).html(row_num);
															$( '#hidden_rows' ).val(row_num);
															$( '#hidden_cols' ).val(col_num);})

	$( '#sizePlus' ).click(function(){
															row_num += 1;
															col_num += 1;
															createInputTable(row_num, col_num);
															$( '#PrintSize' ).html(row_num);
															$( '#hidden_rows' ).val(row_num);
															$( '#hidden_cols' ).val(col_num);})
</script>
<!-- reseni bude v include --!>
<div class='col-md-10 col-sm-9' style='padding-right: 0 !important;'>
{% include 'matrixolver/solution.html' %}
<p>Inverzní matice k matici <math display='inline'><mi>A</mi></math> je taková, která násobením vytvoří z <math display='inline'><mi>A</mi></math> jednotkovou matici. Značíme ji
<math display="inline"><msup><mi>A</mi><mn>-1</mn></msup></math> a platí</p>
<math display="block">
<msup><mi>A</mi><mn>-1</mn></msup><mi>A</mi><mo>=</mo><mi>E</mi>
</math>
<p>kde <math display='inline'><mi>E</mi></math> je jednotková matice.</p>
<p>Výpočet inverzní matice se prování tak, že matici <math display='inline'><mi>A</mi></math> rozšíříme jednotkovou maticí a provádíme ekvivalentní úpravy obou matic tak, abychom z matice <math display='inline'><mi>A</mi></math> dostali matici jednotkovou. Aby bylo možno najít inverzní matici, musí být regulární. Tedy čtvercová a její hodnost musí být stejná, jako počet jejích řádků.</p>
</div>
	</div>
</div>
{% endblock content %}

matrixolver/templates/matrixolver/rank.html
{% extends 'matrixolver/base.html' %}

{% block content %}

<script type='text/javascript'>
	lis = $('ul.nav').find('li');
	lis.removeClass('active');
	$('#rank').addClass('active');
	var row_num = {{ A.row_num }};
	var col_num = {{ A.col_num }};
</script>

<style>
	.affix{ top: 20px; }
</style>
<div class='container-fluid'>
	<div class='row' id='solution_row'>
			<div class='col-md-2 col-sm-3 well sidebar-nav-fixed' style='padding: 19px 0 !important;'>
			<div class='span1'> <!--potreba prijit na to, proc se meni sirka a vyresit overlap pri mensim rozliseni--!>
			<div class='row'>
			<div class='col'>
			<div class='cSize'>
			<table>
			<tr>
				<td style='white-space: nowrap'>Řady: <span id='PrintSizeRows'>{{ A.row_num }}</span>&nbsp&nbsp</td>
				<td>
					<span class="btn-group-xs btn-group-vertical" role="group" aria-label="Velikost matice">
						<button type="button" class="btn btn-primary" id='rowPlus'>+</button>
						<button type="button" class="btn btn-primary" id='rowMinus'>-</button>
					</span>
				</td>
				<td style='white-space: nowrap'>&nbsp Sloupce: <span id='PrintSizeCols'>{{ A.col_num }}</span>&nbsp&nbsp</td>
				<td>
					<span class="btn-group-xs btn-group-vertical" role="group" aria-label="Velikost matice">
						<button type="button" class="btn btn-primary" id='colPlus'>+</button>
						<button type="button" class="btn btn-primary" id='colMinus'>-</button>
					</span>
				</td>
			</tr>
			</table>
			</div>

			</div>
			</div>

			<div class='row'>
			<div class='col'>
				<div class='input-group cInput' id='sidebar'>
				<form action="{% url 'matrixolver:rank_solution' %}" method='POST' name='matrix'>{% csrf_token %}
				<!--form validation--!>
					<table class='table table-bordered table-condensed' id='InputTable'>
					{% for row in A.rows %}
						<tr>{% for element in row %}<td>
				<input class='form-control cInput' type='text' name='a{{ forloop.parentloop.counter0 }}{{ forloop.counter0 }}' onclick='select()' step='any' value='{{ element }}' autocomplete='off' pattern='[-+]?[0-9]*\.?[0-9]*' /></td>{% endfor %}</tr>
					{% endfor %}
					</table>
					<input type='hidden'  id='hidden_rows' name='hidden_rows' value='{{ A.row_num }}' />
					<input type='hidden' id='hidden_cols' name='hidden_cols' value='{{ A.col_num }}' />
					<button type="submit" class='btn btn-primary'>Spočítat hodnost</button>
				</form>
				</div>
			</div>
			</div>
			</div>
		</div>

<script>
	$( '#rowMinus' ).click(function(){
															row_num -= 1;
															createInputTable(row_num, col_num);
															$( '#PrintSizeRows' ).html(row_num);
															$( '#hidden_rows' ).val(row_num);}),

	$( '#rowPlus' ).click(function(){
															row_num += 1;
															createInputTable(row_num, col_num);
															$( '#PrintSizeRows' ).html(row_num);
															$( '#hidden_rows' ).val(row_num);}),

	$( '#colMinus' ).click(function(){
															col_num -= 1;
															createInputTable(row_num, col_num);
															$( '#PrintSizeCols' ).html(col_num);
															$( '#hidden_cols' ).val(col_num);}),

	$( '#colPlus' ).click(function(){
															col_num += 1;
															createInputTable(row_num, col_num);
															$( '#PrintSizeCols' ).html(col_num);
															$( '#hidden_cols' ).val(col_num);})
</script>

<!-- reseni bude v include --!>
<div class='col-md-10 col-sm-9' style='padding-right: 0 !important;'>
{% include 'matrixolver/solution_no_extend.html' %}
<p>Hodnost matice znamená počet jejích lieáně nezávislých řádků. To znamená počet řádků, které nedokážeme vyjádřit jako součet různě vynásobených ostatních řádků. Například matice</p>
<math display='block'>
<mfenced open='[' close=']' separators=''>
    <mtable>
      <mtr>
        <mtd><mn>1</mn></mtd>
        <mtd><mn>2</mn></mtd>
        <mtd><mn>3</mn></mtd>
      </mtr>
      <mtr>
        <mtd><mn>1</mn></mtd>
        <mtd><mn>1</mn></mtd>
        <mtd><mn>2</mn></mtd>
      </mtr>
      <mtr>
        <mtd><mn>3</mn></mtd>
        <mtd><mn>4</mn></mtd>
        <mtd><mn>7</mn></mtd>
      </mtr>
    </mtable>
</mfenced>
</math>
<p>má hodnost pouze 2, protože třetí řádek lze vyjádřit jako součet prvního řádku s dvakrát vynásobeným 2. řádkem.</p>
<p>Hodnost matice zjistíme tak, že dostaneme matici do schodovitého tvaru a spočítáme řádky, které nejsou nulové. Úloha může být někdy zadána tak, že místo některého z čísel je v matici uveden parametr. Hodnost matice poté může záviset na hodnotě tohoto parametru.</p>
</div>
	</div>
</div>
{% endblock content %}